### PR TITLE
Add an options.verboseLogging option to enable/disable logging

### PR DESCRIPTION
**Pull request by batmat**
hello @void666, what do you think about this? I am already wrapping the download part of our code with logging, so I'd like to disable the one coming from your library.

I'm still leaving the error-related ones on purpose. I'm just trying to remove the logs for the nominal case.

Thanks :smile_cat: !

### CODE REVIEW

**Comment by void666** [comment]
@batmat, looks good! However was deliberating whether to use the logger's default logging level instead of adding additional one.

**Comment by batmat** [comment]
@void666 yeah, I guess indeed if you consider that code a library, this shouldn't try and define/use a fancy logging style/formatting, but leave that to the calling system/global config. But I'm still a Node newbie, so, well :).

**Comment by batmat** [comment]
\o/ thanks a bunch @void666. Any possibility of a `1.0.1` release or something with this? 

Thanks again!

**Comment by void666** [comment]
Done already @batmat . Thanks for the contribution.

**Pull request merged**
